// src/components/screens/AuthScreen.tsx
import { TelegramLoginButton, TelegramAuthData } from '@/components/TelegramLoginButton';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2 } from 'lucide-react';

interface AuthScreenProps {
  onLogin: (authData: TelegramAuthData) => void;
  isLoading: boolean;
}

export function AuthScreen({ onLogin, isLoading }: AuthScreenProps) {
  const botUsername = import.meta.env.VITE_TELEGRAM_BOT_USERNAME;

  const handleAuth = (user: TelegramAuthData) => {
    // Dispatch custom event for the hook
    const event = new CustomEvent('telegram-auth', { detail: user });
    window.dispatchEvent(event);
    // Also call onLogin for the parent
    onLogin(user);
  };

  if (!botUsername) {
    return (
      <div className="flex items-center justify-center min-h-screen px-4">
        <Card className="w-full max-w-md">
          <CardHeader>
            <CardTitle>Ошибка конфигурации</CardTitle>
            <CardDescription>
              Не указан username Telegram-бота в переменных окружения.
            </CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  return (
    <div className="flex items-center justify-center min-h-screen px-4 bg-gradient-to-br from-blue-50 to-indigo-100">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl font-bold text-gray-900">
            Echo Connect
          </CardTitle>
          <CardDescription>
            Войдите через Telegram для доступа к звонкам
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {isLoading ? (
            <div className="flex justify-center py-8">
              <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
            </div>
          ) : (
            <TelegramLoginButton
              botName={botUsername}
              onAuth={handleAuth}
              buttonSize="large"
              usePic={true}
            />
          )}
          <p className="text-sm text-gray-600 text-center">
            Авторизуйтесь, чтобы начать общение
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

export default AuthScreen;

// src/components/screens/AuthScreen.vue
<template>
  <div v-if="!botUsername" class="flex items-center justify-center min-h-screen px-4">
    <div class="w-full max-w-md">
      <h1 class="text-xl font-bold">Ошибка конфигурации</h1>
      <p>Не указан username Telegram-бота в переменных окружения.</p>
    </div>
  </div>
  <div v-else class="flex items-center justify-center min-h-screen px-4 bg-gradient-to-br from-blue-50 to-indigo-100">
    <div class="w-full max-w-md">
      <div class="text-center mb-8">
        <h1 class="text-2xl font-bold text-gray-900">Echo Connect</h1>
        <p class="text-gray-600">Войдите через Telegram для доступа к звонкам</p>
      </div>
      <div class="space-y-4">
        <div v-if="isLoading" class="flex justify-center py-8">
          <div class="animate-spin h-8 w-8 border-4 border-blue-600 border-t-transparent rounded-full"></div>
        </div>
        <TelegramLoginButton v-else :bot-name="botUsername" @auth="handleAuth" button-size="large" :use-pic="true" />
        <p class="text-sm text-gray-600 text-center">Авторизуйтесь, чтобы начать общение</p>
        <p class="text-xs text-gray-500 text-center mt-2">Примечание: Убедитесь, что в настройках Telegram-бота установлен домен веб-приложения через /setdomain в BotFather. Для локальной разработки используйте ngrok и установите HTTPS URL.</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import TelegramLoginButton from '@/components/TelegramLoginButton.vue'

interface TelegramAuthData {
  id: number
  first_name: string
  last_name?: string
  username?: string
  photo_url?: string
  auth_date: number
  hash: string
}

interface Props {
  onLogin: (authData: TelegramAuthData) => void
  isLoading: boolean
}

const props = defineProps<Props>()

const botUsername = import.meta.env.VITE_TELEGRAM_BOT_USERNAME

const handleAuth = (user: TelegramAuthData) => {
  const event = new CustomEvent('telegram-auth', { detail: user })
  window.dispatchEvent(event)
  props.onLogin(user)
}
</script>
