// src/pages/Index.vue
<template>
  <div v-if="authError && currentScreen === 'auth'" class="flex items-center justify-center min-h-screen px-4">
    <div class="text-center max-w-md">
      <p class="text-red-500 font-semibold mb-2">Ошибка авторизации</p>
      <p class="text-sm text-muted-foreground mb-4">{{ authError }}</p>
      <p class="text-xs text-muted-foreground">Обновите страницу и попробуйте снова.</p>
    </div>
  </div>
  <AuthScreen v-else-if="currentScreen === 'auth'" :on-login="handleLogin" :is-loading="authLoading" />
  <ContactsScreen v-else-if="currentScreen === 'contacts' && user" :current-user="user" :on-call="handleCall" :on-logout="handleLogout" />
  <CallScreen v-else-if="currentScreen === 'call' && activeCallContact" :contact="activeCallContact" :on-end-call="handleEndCall" :on-accept-call="() => currentScreen = 'call'" />
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import AuthScreen from '@/components/screens/AuthScreen.vue'
import { ContactsScreen } from '@/components/screens/ContactsScreen.vue'
import { CallScreen } from '@/components/screens/CallScreen.vue'
import { useTelegramAuth, TelegramUser } from '@/hooks/useTelegramAuth'
import { User } from '@/types/app'

type Screen = 'auth' | 'contacts' | 'call'

const { user, loading: authLoading, error: authError, logout } = useTelegramAuth()
const currentScreen = ref<Screen>('auth')
const activeCallContact = ref<User | null>(null)

watch(user, (newUser) => {
  currentScreen.value = newUser ? 'contacts' : 'auth'
})

const handleLogin = async (authData: TelegramUser) => {
  console.log('Login successful:', authData)
}

const handleLogout = async () => {
  await logout()
  currentScreen.value = 'auth'
}

const handleCall = (contact: User) => {
  activeCallContact.value = contact
  currentScreen.value = 'call'
}

const handleEndCall = () => {
  activeCallContact.value = null
  currentScreen.value = 'contacts'
}
</script>

// src/pages/Index.tsx
import { useEffect, useState } from 'react';
import AuthScreen from '@/components/screens/AuthScreen';
import { ContactsScreen } from '@/components/screens/ContactsScreen';
import { CallScreen } from '@/components/screens/CallScreen';
import { useTelegramAuth, TelegramUser } from '@/hooks/useTelegramAuth';
import { User } from '@/types/app';

type Screen = 'auth' | 'contacts' | 'call';

const Index = () => {
  const { user, loading: authLoading, error: authError, logout } = useTelegramAuth();
  const [currentScreen, setCurrentScreen] = useState<Screen>('auth');
  const [activeCallContact, setActiveCallContact] = useState<User | null>(null);

  useEffect(() => {
    if (user) setCurrentScreen('contacts');
    else setCurrentScreen('auth');
  }, [user]);

  const handleLogin = async (authData: TelegramUser) => {
    console.log('Login successful:', authData);
  };

  const handleLogout = async () => {
    await logout();
    setCurrentScreen('auth');
  };

  const handleCall = (contact: User) => {
    setActiveCallContact(contact);
    setCurrentScreen('call');
  };

  const handleEndCall = () => {
    setActiveCallContact(null);
    setCurrentScreen('contacts');
  };

  if (authError && currentScreen === 'auth') {
    return (
      <div className="flex items-center justify-center min-h-screen px-4">
        <div className="text-center max-w-md">
          <p className="text-red-500 font-semibold mb-2">Ошибка авторизации</p>
          <p className="text-sm text-muted-foreground mb-4">{authError}</p>
          <p className="text-xs text-muted-foreground">Обновите страницу и попробуйте снова.</p>
        </div>
      </div>
    );
  }

  return (
    <>
      {currentScreen === 'auth' && <AuthScreen onLogin={handleLogin} isLoading={authLoading} />}
      {currentScreen === 'contacts' && user && (
        <ContactsScreen
          currentUser={user as TelegramUser}
          onCall={handleCall}
          onLogout={handleLogout}
        />
      )}
      {currentScreen === 'call' && activeCallContact && (
        <CallScreen
          contact={activeCallContact}
          onEndCall={handleEndCall}
          onAcceptCall={() => setCurrentScreen('call')}
        />
      )}
    </>
  );
};

export default Index;
